- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: install composer
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

- name: rename composer.phar to composer
  sudo: yes
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: make composer executable
  sudo: yes
  file: path=/usr/local/bin/composer mode=a+x state=file